### ISSUE TITLE
Microsoft-NanoServer-IIS-Package and Microsoft-NanoServer-SCVMM-Package cannot be installed online

### ISSUE THREAD

**Issue by quoctruong** [OneGet/NanoServerPackage#2]
These packages can only be installed offline OR they can only be installed online if user already installs a package that requires reboot.

**Comment by artisticcheese** [comment]
What does it mean "OR they can only be installed online if user already installs package that requries reboot"? I'm trying to install IIS and getting error mentioned in Readme doc which I assumed due to missing dependencies.

**Comment by quoctruong** [comment]
Hi @artisticcheese, there are some problems with the "Microsoft-NanoServer-IIS-Package". If you try to install something like "Microsoft-NanoServer-Storage-Package" first (which will issue a warning saying that you need to reboot the machine), then you can try install "Microsoft-NanoServer-IIS-Package" and it will succeed. We already have plan to fix this for the next release.

**Comment by anweiss** [comment]
hey @quoctruong ... along those lines, I'm installing the "Microsoft-NanoServer-IIS-Package" in a nanoserver container, but the w3svc doesn't seem to want to start due to the following error:

`Microsoft-Windows-WAS cannot be found`

Is this a known issue with the IIS package?

**Comment by shirhatti** [comment]
@quoctruong Has this been fixed in the eval version on Windows Server?

**Comment by jianyunt** [comment]
@xumins, Microsoft-Windows-WAS is supposed to be in the package list?

**Comment by xumins** [comment]
all are fixed in the provider version 1.0.1.0. Please update your Nano Server to WS2016 GA version 10.0.14393.0, then install NanoServerPackage provider 1.0.1.0 from PowerShellGallery.com.
